# SonarCloud Configuration
sonar.projectKey=SE-Project
sonar.organization=thedanah

# Sources
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=node_modules/**,dist/**,.git/**,coverage/**

# Language
sonar.language=js

# JavaScript specific
sonar.javascript.lcov.reportPaths=coverage/lcov.info
